name: crypto_info
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^27.2.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_laucher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 17

flutter:
  uses-material-design: true

  assets:
    - assets/dictionary_data.json
    - assets/profile_picture.png
    - assets/icon/icon.png